// Validate pipeline output against saved ground truth.
// Run: deno test --no-check --allow-read tests/ground_truth_test.ts
//
// Ground truth generated by: deno run --allow-read --allow-write tests/gen_ground_truth.ts

import { assert } from 'https://deno.land/std@0.208.0/assert/assert.ts';
import { runPipeline } from '../docs/blitzoom-pipeline.js';
import { unifiedBlend, MINHASH_K } from '../docs/blitzoom-algo.js';

interface GTCase {
  name: string;
  edges: string;
  nodes: string | null;
  strengths: Record<string, number>;
  alpha: number;
  quant: string;
}

const cases: GTCase[] = [
  { name: 'karate-balanced', edges: 'docs/data/karate.edges', nodes: 'docs/data/karate.nodes',
    strengths: { group: 3, label: 1 }, alpha: 0, quant: 'gaussian' },
  { name: 'karate-topo', edges: 'docs/data/karate.edges', nodes: 'docs/data/karate.nodes',
    strengths: { group: 3, label: 1 }, alpha: 0.75, quant: 'gaussian' },
  { name: 'epstein-edgetype', edges: 'docs/data/epstein.edges', nodes: 'docs/data/epstein.nodes',
    strengths: { group: 5, edgetype: 8 }, alpha: 0, quant: 'gaussian' },
  { name: 'epstein-topo', edges: 'docs/data/epstein.edges', nodes: 'docs/data/epstein.nodes',
    strengths: { group: 5, edgetype: 8 }, alpha: 0.75, quant: 'gaussian' },
{ name: 'mitre-weighted', edges: 'docs/data/mitre-attack.edges', nodes: 'docs/data/mitre-attack.nodes',
    strengths: { group: 5, platforms: 6, killchain: 4 }, alpha: 0, quant: 'gaussian' },
  { name: 'mitre-rank', edges: 'docs/data/mitre-attack.edges', nodes: 'docs/data/mitre-attack.nodes',
    strengths: { group: 5, platforms: 6, killchain: 4 }, alpha: 0, quant: 'rank' },
  { name: 'email-topo', edges: 'docs/data/email-eu.edges', nodes: null,
    strengths: {}, alpha: 0.75, quant: 'rank' },
];

function loadGroundTruth(name: string) {
  const text = Deno.readTextFileSync(`tests/ground-truth/${name}.tsv`);
  const lines = text.split('\n').filter(l => l && !l.startsWith('#'));
  const entries: Record<string, { px: number; py: number; gx: number; gy: number }> = {};
  for (const line of lines) {
    const parts = line.split('\t');
    entries[parts[0]] = {
      px: parseFloat(parts[1]),
      py: parseFloat(parts[2]),
      gx: parseInt(parts[3]),
      gy: parseInt(parts[4]),
    };
  }
  return entries;
}

for (const tc of cases) {
  Deno.test(`Ground truth: ${tc.name}`, () => {
    const gt = loadGroundTruth(tc.name);
    const edgesText = Deno.readTextFileSync(tc.edges);
    const nodesText = tc.nodes ? Deno.readTextFileSync(tc.nodes) : null;
    const result = runPipeline(edgesText, nodesText);

    const G = result.groupNames.length;
    const nodes = result.nodeArray.map((n: any, i: number) => {
      const projections: Record<string, number[]> = {};
      for (let g = 0; g < G; g++) {
        const off = (i * G + g) * 2;
        projections[result.groupNames[g]] = [result.projBuf[off], result.projBuf[off + 1]];
      }
      return { ...n, projections, px: 0, py: 0, gx: 0, gy: 0 };
    });

    const adjList: Record<string, string[]> = {};
    for (const n of nodes) adjList[n.id] = [];
    for (const e of result.edges) {
      if (adjList[e.src] && adjList[e.dst]) {
        adjList[e.src].push(e.dst);
        adjList[e.dst].push(e.src);
      }
    }
    const nodeIndexFull: Record<string, any> = {};
    for (const n of nodes) nodeIndexFull[n.id] = n;

    const propStrengths: Record<string, number> = {};
    for (const g of result.groupNames) propStrengths[g] = tc.strengths[g] ?? 0;

    unifiedBlend(nodes, result.groupNames, propStrengths, tc.alpha, adjList, nodeIndexFull, 5, tc.quant, {});

    // Compare
    let maxPxDelta = 0, maxGyDelta = 0, gxMismatches = 0;
    for (const n of nodes) {
      const g = gt[n.id];
      if (!g) continue;
      const dpx = Math.abs(n.px - g.px);
      const dpy = Math.abs(n.py - g.py);
      maxPxDelta = Math.max(maxPxDelta, dpx, dpy);
      const dgx = Math.abs(n.gx - g.gx);
      const dgy = Math.abs(n.gy - g.gy);
      maxGyDelta = Math.max(maxGyDelta, dgx, dgy);
      if (dgx > 0 || dgy > 0) gxMismatches++;
    }

    console.log(`  ${tc.name}: maxPxDelta=${maxPxDelta.toFixed(10)}, maxGxDelta=${maxGyDelta}, gxMismatches=${gxMismatches}/${nodes.length}`);
    assert(maxPxDelta === 0, `px/py should be bit-identical but maxDelta=${maxPxDelta}`);
    assert(maxGyDelta === 0, `gx/gy should be bit-identical but maxDelta=${maxGyDelta}`);
  });
}
